# Generated by Django 3.1.4 on 2021-01-02 16:25

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_demopost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopost',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=blogs.models.upload_to, verbose_name='Image'),
        ),
    ]
